# Generated by Django 4.2.23 on 2025-07-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('addres', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
    ]
