# Generated by Django 4.2.23 on 2025-07-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='addres',
        ),
        migrations.AddField(
            model_name='company',
            name='nomer',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='company',
            name='sity',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='ulica',
            field=models.CharField(default='', max_length=100),
        ),
    ]
