# Generated by Django 4.2.23 on 2025-07-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_remove_company_addres_company_nomer_company_sity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
                ('in_footer', models.BooleanField()),
                ('on_nav', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='nomer',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='company',
            name='sity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='ulica',
            field=models.CharField(max_length=100),
        ),
    ]
