# Generated by Django 4.2.23 on 2025-07-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_nav_alter_company_nomer_alter_company_sity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nav',
            name='type',
        ),
        migrations.AddField(
            model_name='nav',
            name='page_type',
            field=models.CharField(choices=[('1', 'Галерия'), ('2', 'Промоция'), ('3', 'Въпрос'), ('4', 'Друго')], default='1', max_length=5),
        ),
    ]
