# Generated by Django 4.2.23 on 2025-07-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_remove_nav_type_nav_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='page_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
