# Generated by Django 4.2.23 on 2025-07-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_nav_page_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmptyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
    ]
