# Generated by Django 4.2.23 on 2025-07-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_emptypage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=50)),
            ],
        ),
    ]
