# Generated by Django 4.2.23 on 2025-07-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_galery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('from_price', models.FloatField()),
                ('to_price', models.FloatField()),
                ('img_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='galery',
            name='img_url',
            field=models.CharField(max_length=100),
        ),
    ]
