# Generated by Django 4.2.23 on 2025-07-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='in_nav',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='in_index',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='promotion',
            name='in_nav',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='in_nav',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
